name: practiceAction 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
      
      - name: echo message
        run: echo "Hello, this is a practice action workflow!"